spring:
  application:
    name: realtime-vehicle-tracking
  kafka:
    bootstrap-servers: "broker:29092"
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://schema-registry:8081"
kafka:
  topic:
    name: "spring.boot.vehicle.position.kafka.topic.v1"
